experiment_name: gsm8k-grpo
trial_name: trial0
allocation_mode: sglang.d4p1t1+d4p1t1
cluster:
  fileroot: /tmp/areal/experiments
  n_nodes: 1
  n_gpus_per_node: 8
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/areal/name_resolve
seed: 1
total_train_epochs: 10
tokenizer_path: ${actor.path}
async_training: true

# datasets
train_dataset:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: areal/bfcl/data
  type: rl
  max_length: 4096

valid_dataset:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: openai/gsm8k
  type: rl

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 64
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  enable_rollout_tracing: false


