wandb:
  mode: disabled
mode: ray
max_head_offpolicyness: 4
experiment_name: async-ppo-throughput
max_concurrent_rollouts: 512
exp_ctrl:
  total_train_epochs: 10
  benchmark_n_seqs: 5120
actor:
  type:
    _class: qwen2
  sglang:
    mem_fraction_static: 0.8
    context_length: 32768
dataset:
  path: /storage/testing/dataset/boba_106k_0319.jsonl
  max_prompt_len: 1024
  train_bs_n_seqs: 512
group_size: 16
ppo:
  gen:
    min_new_tokens: 0
    temperature: 1.0
  recompute_logprob: true
  use_decoupled_loss: true
  disable_value: true
  ppo_n_minibatches: 4
  kl_ctl: 0.0
  value_eps_clip: 0.2
actor_train:
  mb_spec:
    max_tokens_per_mb: 32768
actor_inf:
  mb_spec:
    max_tokens_per_mb: 32768
n_gpus_per_node: 8
cache_clear_freq: 1
recover_mode: disabled
recover_retries: 10
torch_cache_mysophobia: true