name: Test AReaL

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-areal:
    environment:
      name: AReaL-unittests
    permissions:
      contents: read
    runs-on: gpu
    timeout-minutes: 7200
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          source examples/env/scripts/setup-pip-deps.sh

      - name: Wait for GPU
        timeout-minutes: 7200
        run: |
          ALL_DEVICES="$(nvidia-smi --query-gpu=index --format=csv,noheader,nounits | tr '\n' ',' | sed 's/,$//')"
            
          until [[ "$CUDA_VISIBLE_DEVICES" == "$ALL_DEVICES" ]]; do
            CUDA_VISIBLE_DEVICES="$(nvidia-smi --query-gpu=index,memory.free,memory.total --format=csv,noheader,nounits | awk -F',' '$2/$3 >= 0.90 {print $1}' | tr '\n' ',' | sed 's/,$//')"
            sleep 1
          done
          
          echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES" >> "$GITHUB_ENV"

      - env:
          CI: true
        run: |
          pytest areal/tests
